### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by GrimPixel** [Blackprint/Blackprint#3]
```
> @blackprint/sketch@0.8.13 compile
> gulp compile

Error: Cannot find module './editor/utils/build-docs.js'
Require stack:
- /home/user/Blackprint/gulpfile.js
- /home/user/Blackprint/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/shared/require-or-import.js
- /home/user/Blackprint/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /home/user/Blackprint/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/index.js
- /home/user/Blackprint/node_modules/.pnpm/gulp@4.0.2/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/user/Blackprint/gulpfile.js:113:3)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/Blackprint/gulpfile.js',
    '/home/user/Blackprint/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/home/user/Blackprint/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/home/user/Blackprint/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/index.js',
    '/home/user/Blackprint/node_modules/.pnpm/gulp@4.0.2/node_modules/gulp/bin/gulp.js'
  ]
}
```

**Comment by StefansArya** [comment]
Hi!
It seems `./editor/utils/build-docs.js` was missing from your working directory.
Because the `editor` in this repo is a sub-module, you will need to clone this repo with command like below:

```sh
$ git clone --depth 1 --recurse-submodules https://github.com/Blackprint/Blackprint.git .
```

1. `--recurse-submodules` is required to clone the submodule
2. `--depth 1` is used to just download the latest commit and it's optional

The [readme](https://github.com/Blackprint/Blackprint#contributing) also has instruction to start the server, but you can also use the [deployed online editor](https://blackprint.github.io/) to quickly launch the editor.

Using online editor will require you to connect into your module server if you want to create your own nodes/module. But if you're using this local editor, you can also begin prototyping your own nodes by put the module folder to `./nodes` folder.

```sh
# Make sure '@blackprint/cli-tools' already installed and updated globally
$ cd ./nodes/your-new-folder
$ blackprint create
# And then go to the editor without restarting the local editor's compiler, the modules is hot reloaded
```

**Comment by GrimPixel** [comment]
Thank you for your help. That was the reason. I didn't know about that submodule.

Now there is a new one:
```
> @blackprint/sketch@0.8.13 compile
> gulp compile

/home/grim/Blackprint/editor/utils/build-docs.js:14
		let ref = obj[temp] ??= {branch: {}};
		                    ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/grim/Blackprint/gulpfile.js:113:3)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
```

**Comment by StefansArya** [comment]
Hmm, it's `Nullish coalescing assignment` that was available after Node.js v15.
It's recommend to update the Node.js on your system to the LTS version (currently: v18).

In case you need to use your current version for older project, you can also use [nvm](https://github.com/nvm-sh/nvm#intro) as version manager to switch between Node.js version. But if you don't, then just installing the LTS version is also okay.

**Comment by GrimPixel** [comment]
You are experienced. It's done! Great!
